### ISSUE TITLE
How does this compare to an ALB pointing directly to a lambda?

### ISSUE THREAD

**Issue by scastria** [aws-samples/serverless-samples#27]
I was playing around with this and I noticed that a lambda function can be a target group for an ALB.  I create an R53 record pointing to ALB which had an HTTPS listener with proper certificate and target group containing my lambda.  And it WORKED!

Therefore, I am wondering how my approach compares with this repo's approach.  I didn't even have to touch API Gateway at all.  But keep in mind, my lambda does nothing except return a redirect URL.  Therefore, it doesn't have to process URL paths, query parameters, or request bodies so maybe that is why API Gateway is not necessary?

**Comment by giedri** [comment]
It depends on your use case. If you just need to invoke AWS Lambda function or build simple API, ALB or Lambda function URL will work just fine. You would use Amazon API Gateway when you need API management features, not just an endpoint.
